//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apuesta
    {
        public int idApuesta { get; set; }
        public int idEvento { get; set; }
        public int idJugador { get; set; }
        public decimal cantidad { get; set; }
        public System.DateTime fecha { get; set; }
        public string prediccion { get; set; }
        public Nullable<bool> resultado { get; set; }
    
        public virtual Evento Evento { get; set; }
        public virtual Jugador Jugador { get; set; }
    }
}
