//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PlexusDBEntities : DbContext
    {
        public PlexusDBEntities()
            : base("name=PlexusDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Apuesta> Apuesta { get; set; }
        public virtual DbSet<Evento> Evento { get; set; }
        public virtual DbSet<Jugador> Jugador { get; set; }
        public virtual DbSet<Monedero> Monedero { get; set; }
    }
}
